// <auto-generated />
using KwikKwekSnek.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KwikKwekSnek.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KwikKwekSnek.Models.Drankje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("afbeelding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("grootte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ijs")
                        .HasColumnType("bit");

                    b.Property<bool>("plasticrietje")
                        .HasColumnType("bit");

                    b.Property<decimal>("prijs")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("drankjes");
                });
#pragma warning restore 612, 618
        }
    }
}
